[[redirects]]
  from = "/pathx"
  to = "https://server-geoipm.vercel.app/api/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"